import './layout/main.scss'
import './blocks/like-button/like-button.js'
import './blocks/expandable-checkbox-list/expandable-checkbox-list.js'
import './blocks/range-slider/range-slider.js'
import './blocks/rate-button/rate-button.js'
import './blocks/dropdown/dropdown.js'